# Generated by Django 3.2.23 on 2024-01-02 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='reader_uid',
            field=models.CharField(default=123, max_length=128),
            preserve_default=False,
        ),
    ]
