# Generated by Django 3.2.23 on 2023-12-22 21:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('swipe_count', models.IntegerField()),
                ('reader_uid', models.CharField(max_length=24)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
