# Generated by Django 3.2.23 on 2024-01-07 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_user_transaction_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='created_by',
            new_name='requested_by',
        ),
    ]
