# Generated by Django 3.2.23 on 2024-01-07 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_rename_created_by_transaction_requested_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='grant_type',
            field=models.CharField(default='ACCESS GRANTED', max_length=25),
            preserve_default=False,
        ),
    ]
