# Generated by Django 3.2.23 on 2024-01-07 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_transaction_grant_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='requested_by',
            new_name='approved_by',
        ),
    ]
