# Generated by Django 3.2.23 on 2024-01-07 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_rename_requested_by_transaction_approved_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='approved_by',
            new_name='authorizer',
        ),
    ]
