# Generated by Django 3.2.23 on 2024-01-08 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_rename_approved_by_transaction_authorizer'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='door',
            field=models.CharField(default='esp-rfid', max_length=128),
            preserve_default=False,
        ),
    ]
